plugins:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.4
  Exclude:
    - Gemfile
    - 'vendor/**/*'
  NewCops: enable

# Layout

Layout/LineLength:
  Max: 130

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Metrics

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 35

# Naming

Naming/VariableNumber:
  Enabled: false

# Style

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

# RSpec

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

RSpec/NoExpectationExample:
  Enabled: false

# Rails

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/ThreeStateBooleanColumn:
  Enabled: false

Rails/Output:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/TimeZone:
  Enabled: false
